name: Weekly Build and Upload

on:
  schedule:
    - cron: "0 0 * * 1"  # Uruchamia się o północy w poniedziałek

jobs:
  build-and-upload:
    runs-on: windows-latest


    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        shell: powershell

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
        shell: powershell

      - name: Configure and install resources
        run: |
          python installResources.py
        shell: powershell

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole project.py
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/project.exe
        shell: powershell

      - name: Upload to GitHub repository
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/project.exe
          retention-days: 7
          repository: MateuszKrolik/Lab678
        shell: powershell

  build_unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
        shell: bash

      - name: Configure and install resources
        run: |
          python installResources.py
        shell: bash

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole project.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/project.exe
        shell: bash

      - name: Upload to GitHub repository
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/project.exe
          retention-days: 7
          repository: MateuszKrolik/Lab678
        shell: bash

